[workspace]
resolver = "2"

members = ["day-*"]
default-members = ["day-*"]

[workspace.dependencies]
nom = "7.1.3"
nom-supreme = "0.8.0"
glam = "0.24.2"
nom_locate = "4.2.0"
itertools = "0.12.0"
indoc = "2.0.4"
